### ISSUE TITLE
missing field `vector_size` during run qdrant benchmark

### ISSUE THREAD

**Issue by MochiXu** [qdrant/vector-db-benchmark#32]
using qdrant-client-0.11.1 cannot run quadrant benchmark, exception happened during recreate collection
code is in vector-db-benchmark/engine/clients/qdrant/configure.py
```python
def recreate(
        self,
        distance,
        vector_size,
        collection_params,
    ):
        print("distance {}, vector_size {}, collection_params {}".format(distance,vector_size,collection_params))
        self.client.recreate_collection(
            collection_name=QDRANT_COLLECTION_NAME,
            vectors_config=rest.VectorParams(size=vector_size,distance=self.DISTANCE_MAPPING.get(distance)),
            # vector_size=vector_size,
            # distance=self.DISTANCE_MAPPING.get(distance),
            **self.collection_params
        )
```
this is my exception:
```shell
distance cosine, vector_size 25, collection_params {'optimizers_config': {'memmap_threshold': 10000000}}
Traceback (most recent call last):

  File "run.py", line 56, in <module>
    app()

  File "run.py", line 49, in run
    client.run_experiment(dataset, skip_upload)

  File "/home/ubuntu/workspaceBench/vector-db-benchmark/engine/base_client/client.py", line 86, in run_experiment
    self.configurator.configure(

  File "/home/ubuntu/workspaceBench/vector-db-benchmark/engine/base_client/configure.py", line 20, in configure
    return self.recreate(distance, vector_size, self.collection_params) or {}

  File "/home/ubuntu/workspaceBench/vector-db-benchmark/engine/clients/qdrant/configure.py", line 31, in recreate
    self.client.recreate_collection(

  File "/home/ubuntu/.local/lib/python3.8/site-packages/qdrant_client/qdrant_client.py", line 1191, in recreate_collection
    self.http.collections_api.create_collection(

  File "/home/ubuntu/.local/lib/python3.8/site-packages/qdrant_client/http/api/collections_api.py", line 618, in create_collection
    return self._build_for_create_collection(

  File "/home/ubuntu/.local/lib/python3.8/site-packages/qdrant_client/http/api/collections_api.py", line 193, in _build_for_create_collection
    return self.api_client.request(

  File "/home/ubuntu/.local/lib/python3.8/site-packages/qdrant_client/http/api_client.py", line 68, in request
    return self.send(request, type_)

  File "/home/ubuntu/.local/lib/python3.8/site-packages/qdrant_client/http/api_client.py", line 91, in send
    raise UnexpectedResponse.for_response(response)

qdrant_client.http.exceptions.UnexpectedResponse: Unexpected Response: 422 (Unprocessable Entity)
Raw response content:
b'{"result":null,"status":{"error":"Json deserialize error: missing field `vector_size` at line 1 column 224"},"time":0.0}'
```

It's there any solution to solve this problem? Thank you very much

**Comment by kacperlukawski** [comment]
@MochiXu I think that is caused by using different versions of the server and client. Do you use Qdrant 0.8.6, as declared in docker-compose.yaml?
