### ISSUE TITLE
ann-filter-datasets arxiv-titles-384-angular doesn't support milvus

### ISSUE THREAD

**Issue by MochiXu** [qdrant/vector-db-benchmark#44]
When I use vector-db-benchmark to test milvus filter performance, it raise the exception below. 
The dataset is [arxiv-titles-384-angular
](https://github.com/qdrant/ann-filtering-benchmark-datasets)

But I see that qdrant did complete the filter testing of milvus, how can I reproduce the result?

```shell
❯ python run.py
Running experiment: milvus-default - arxiv-titles-384-angular-filters
established connection
/Users/mochix/workspace_mqdb_github/vector-db-benchmark/datasets/arxiv-titles-384-angular/arxiv already exists
Experiment stage: Configure
Experiment stage: Upload
E0317 16:08:15.044200000 4343137664 fork_posix.cc:76]                  Other threads are currently calling into gRPC, skipping fork() handlers
191it [00:05, 37.15it/s]
Experiment milvus-default - arxiv-titles-384-angular-filters interrupted
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/Users/mochix/opt/anaconda3/envs/python_sdk_local/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/mochix/workspace_mqdb_github/vector-db-benchmark/engine/base_client/upload.py", line 86, in _upload_batch
    cls.upload_batch(ids, vectors, metadata)
  File "/Users/mochix/workspace_mqdb_github/vector-db-benchmark/engine/clients/milvus/upload.py", line 58, in upload_batch
    cls.collection.insert([ids, vectors] + field_values)
  File "/Users/mochix/opt/anaconda3/envs/python_sdk_local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 544, in insert
    if not self._check_insert_data_schema(data):
  File "/Users/mochix/opt/anaconda3/envs/python_sdk_local/lib/python3.8/site-packages/pymilvus/orm/collection.py", line 174, in _check_insert_data_schema
    infer_fields = parse_fields_from_data(data)
  File "/Users/mochix/opt/anaconda3/envs/python_sdk_local/lib/python3.8/site-packages/pymilvus/orm/schema.py", line 300, in parse_fields_from_data
    fields.append(FieldSchema("", d_type))
  File "/Users/mochix/opt/anaconda3/envs/python_sdk_local/lib/python3.8/site-packages/pymilvus/orm/schema.py", line 175, in __init__
    raise DataTypeNotSupportException(0, ExceptionsMessage.FieldDtype)
pymilvus.exceptions.DataTypeNotSupportException: <DataTypeNotSupportException: (code=0, message=Field dtype must be of DataType)>
"""

```

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/42711279/225850219-c0cd399b-da36-4aed-8a5c-e184ebd64a18.png">

**Comment by MochiXu** [comment]
I'm very thankful for your help.
