### ISSUE TITLE
multiTenancyConfig property on weaviate schema requires updating the underlying weaviate-client

### ISSUE THREAD

**Issue by filipecosta90** [qdrant/vector-db-benchmark#53]
sample traceback:

```
Traceback (most recent call last):
  File "/root/vector-db-benchmark/run.py", line 52, in run
    client.run_experiment(dataset, skip_upload, skip_search)
  File "/root/vector-db-benchmark/engine/base_client/client.py", line 92, in run_experiment
    search_stats = searcher.search_all(
  File "/root/vector-db-benchmark/engine/base_client/search.py", line 70, in search_all
    self.setup_search()
  File "/root/vector-db-benchmark/engine/clients/weaviate/search.py", line 59, in setup_search
    self.client.schema.update_config(WEAVIATE_CLASS_NAME, self.search_params)
  File "/usr/local/lib/python3.9/dist-packages/weaviate/schema/crud_schema.py", line 389, in update_config
    check_class(new_class_schema)
  File "/usr/local/lib/python3.9/dist-packages/weaviate/schema/validate_schema.py", line 85, in check_class
    raise SchemaValidationException(f'"{key}" is not a known class definition key.')
weaviate.exceptions.SchemaValidationException: "multiTenancyConfig" is not a known class definition key.
Traceback (most recent call last):

  File "/root/vector-db-benchmark/run.py", line 79, in <module>
    app()

  File "/root/vector-db-benchmark/run.py", line 74, in run
    raise e

  File "/root/vector-db-benchmark/run.py", line 52, in run
    client.run_experiment(dataset, skip_upload, skip_search)

  File "/root/vector-db-benchmark/engine/base_client/client.py", line 92, in run_experiment
    search_stats = searcher.search_all(

  File "/root/vector-db-benchmark/engine/base_client/search.py", line 70, in search_all
    self.setup_search()

  File "/root/vector-db-benchmark/engine/clients/weaviate/search.py", line 59, in setup_search
    self.client.schema.update_config(WEAVIATE_CLASS_NAME, self.search_params)

  File "/usr/local/lib/python3.9/dist-packages/weaviate/schema/crud_schema.py", line 389, in update_config
    check_class(new_class_schema)

  File "/usr/local/lib/python3.9/dist-packages/weaviate/schema/validate_schema.py", line 85, in check_class
    raise SchemaValidationException(f'"{key}" is not a known class definition key.')

weaviate.exceptions.SchemaValidationException: "multiTenancyConfig" is not a known class definition key.
```

PR on weviate python client that includes a fix for it https://github.com/weaviate/weaviate-python-client/pull/345/files#diff-483705e2bda4efc3baf0ca6031a1a949adf864e7ae89813e9139f2843250fd12R19

This means the client needs to be updated to https://github.com/weaviate/weaviate-python-client/releases/tag/v3.22.0

**Comment by KShivendu** [comment]
We recently upgraded to `3.24.2` (See [this](https://github.com/qdrant/vector-db-benchmark/blob/master/pyproject.toml#L13)). 

So I'm marking this as complete. Thanks for creating an issue for this.
